version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements: []
    - requirements: doc/sphinx/requirements.txt
  system_packages: true
build:
  os: ubuntu-22.04
  tools:
    python: "3.6"
sphinx:
  builder: html
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: false