version: 2

python:
  version: "3.8"
  install:
    - requirements: doc/sphinx/requirements.txt
    - method: pip
      path: .
      extra_requirements: []
  system_packages: true
build:
  image: latest
sphinx:
  builder: html
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: false