version: 2

python:
  install:
    - requirements: doc/sphinx/requirements.txt
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
sphinx:
  builder: html
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: false