name: Upload to Zenodo

on:
  release:
    types: [published]

jobs:
  zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to Zenodo
        uses: rseng/zenodo-release@master
        with:
          token: ${{ secrets.ZENODO_TOKEN }}
          version: ${{ github.ref_name }}
          doi: 10.5281/zenodo.4957738
